.TH PERSY 1 "Aug 9, 2009"
.SH NAME
persy \- personal sync
.SH DESCRIPTION
persy can be used just to backup your data or sync your data with multiple
machines. persy is designed to run by its own on a computer as a revision based
backup application or in an environment with multiple computers and at least
one server to keep files and folder in sync between them.
.SH OPTIONS
look at persy --help for more information about options

.SH SEE ALSO
Persy on Github: <http://github.com/kinkerl/persy>
.SH AUTHOR
persy was written by Dennis Schwertel <s@digitalkultur.net>.
